name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test publishing workflow
        run: yarn test:publishing
      - name: Check publishing guardrails
        run: yarn check:publishing
      - name: Test build website
        run: yarn build
